# Generated by Django 4.2.6 on 2023-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_info', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=150)),
                ('monthly_premium', models.IntegerField()),
                ('policy_id', models.CharField(max_length=20, unique=True)),
                ('model_name', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=150)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_birth', models.CharField(max_length=30)),
                ('imei', models.IntegerField()),
                ('serial_number', models.IntegerField(max_length=30)),
                ('initial_call', models.DateField()),
                ('date_joined', models.DateField()),
                ('date_closed', models.DateField()),
                ('insurance_company', models.CharField(max_length=5)),
                ('insurance_status', models.CharField(max_length=10)),
                ('untact_solution', models.IntegerField()),
                ('is_promoted', models.CharField(max_length=5)),
            ],
        ),
    ]
