# Generated by Django 4.2.6 on 2023-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
