# Generated by Django 4.2.6 on 2023-12-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_rename_product_info_info_product_id_alter_info_imei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_closed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='imei',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='initial_call',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='insurance_company',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='insurance_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='is_promoted',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='serial_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='untact_solution',
            field=models.BigIntegerField(null=True),
        ),
    ]
