# Generated by Django 4.2.6 on 2023-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_info_date_closed_alter_info_imei_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='info',
            index=models.Index(fields=['date_joined'], name='member_info_date_jo_4324b3_idx'),
        ),
    ]
